# Generated by Django 2.0 on 2019-10-23 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191021_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referal',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
